### ISSUE TITLE
Publishing fork under a new name

### ISSUE THREAD

**Issue by Fedeorlandau** [weiran-zsd/tsdx#14]
First let me thank you for your amazing work on this fork.

It would be nice that all of this effort gets more recognition. It's actually not that straightforward to land on this repository.

Have you considered publishing this package under a new name?

Regards,

**Comment by aladdin-add** [comment]
I'm open to change it, do you have a better name? 😄

**Comment by SidRathi47** [comment]
@aladdin-add Hello Man i loved your work, i have also been working on bringing this project back to live.

Are you interested in a chat? I think @Fedeorlandau is right, it would be best to bring the changes and improvements under a new name as it will be simpler to distinguish. How about TS-build? actually I have been playing around esbuild trying to implement something like tsdx but when I saw your fork I thought it's better to learn and contribute here only.

Btw I think it's best to ditch parcel for the example playground as it's bringing some issues and breaking HMR.

**Comment by SidRathi47** [comment]
Due to this issue, i decided to replace it with Vite, a build tool which uses esBuild and rollup both. and with a few changes, the dev server including HMR works like a charm

**Comment by SidRathi47** [comment]
![image](https://user-images.githubusercontent.com/58144379/132031192-06c25576-6b9e-4438-a82a-fea07cbfa8b4.png)

**Comment by aladdin-add** [comment]
> How about TS-build?

:+1 SGTM!

let's chat here: https://discord.gg/fMDeSvvm2p

**Comment by Fedeorlandau** [comment]
ts-publish (tsp) is my recommendation since this is for publishing ts packages lol

**Comment by aladdin-add** [comment]
`ts-publish`, and `ts-builder` has been taken. 😢 

@sidwebworks recommended `ts-build` but it was already taken, and tsdx is not just building. so, we prefer `dts-cli`(`dts`). it has two meanings:

1. develop typescript
2. develop + test + ship

just let me know what you think. :)

**Comment by Fedeorlandau** [comment]
Sounds great!

**Comment by sidwebworks** [comment]
Alright guys, got the first PR going! let's see how it goes

**Comment by aladdin-add** [comment]
[dts-cli](https://www.npmjs.com/package/dts-cli) v0.17.0 was released. :🎉
